# Generated by Django 4.2.6 on 2024-07-31 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_theater_remove_reservation_movie_remove_seat_movie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='showtime',
            name='format',
            field=models.CharField(choices=[('2D', '2D'), ('3D', '3D')], default='2D', max_length=2),
        ),
    ]
