# Generated by Django 4.2.6 on 2024-07-31 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_showtime_format'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='showtime',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='showtime',
        ),
        migrations.AddField(
            model_name='reservation',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movies.movie'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seat',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='movies.movie'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Showtime',
        ),
        migrations.DeleteModel(
            name='Theater',
        ),
    ]
