# Generated by Django 4.2.6 on 2024-07-31 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_remove_reservation_showtime_remove_seat_showtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='format',
            field=models.CharField(choices=[('2D', '2D'), ('3D', '3D')], default=None, max_length=2),
        ),
        migrations.AddField(
            model_name='movie',
            name='hall_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.CreateModel(
            name='Showtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showtime', models.DateTimeField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showtimes', to='movies.movie')),
            ],
        ),
    ]
