# Generated by Django 4.2.6 on 2024-08-01 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_movie_format_movie_hall_name_showtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='showtimes',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='cinema_listing',
            field=models.ImageField(null=True, upload_to='movies/cinema_listing/'),
        ),
        migrations.AlterField(
            model_name='showtime',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showtime_entries', to='movies.movie'),
        ),
    ]
