# Generated by Django 4.2.6 on 2024-08-01 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_movie_showtimes_alter_movie_cinema_listing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='showtimes',
        ),
        migrations.AlterField(
            model_name='showtime',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showtimes', to='movies.movie'),
        ),
    ]
