# Generated by Django 4.2.6 on 2024-08-01 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_remove_movie_showtimes_alter_showtime_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='format',
        ),
        migrations.AddField(
            model_name='movie',
            name='formats',
            field=models.ManyToManyField(to='movies.format'),
        ),
    ]
