# Generated by Django 4.2.6 on 2024-08-02 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0017_alter_movie_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='format',
            field=models.CharField(choices=[('2D', '2D'), ('3D', '3D')], default=None, max_length=2),
        ),
    ]
