# Generated by Django 4.2.6 on 2024-08-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0020_alter_movie_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='format',
            field=models.CharField(choices=[('2D', '2D'), ('3D', '3D')], max_length=2),
        ),
        migrations.AlterField(
            model_name='movie',
            name='hall_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(max_length=25),
        ),
    ]
