# Generated by Django 4.2.6 on 2024-08-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0021_alter_movie_format_alter_movie_hall_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='language',
        ),
        migrations.AlterField(
            model_name='movie',
            name='format',
            field=models.CharField(choices=[('2D', '2D'), ('3D', '3D')], default=None, max_length=2),
        ),
        migrations.AlterField(
            model_name='movie',
            name='hall_name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
