# Generated by Django 4.2.6 on 2024-08-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0022_remove_movie_language_alter_movie_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='duration',
            field=models.CharField(default=' ', max_length=10),
        ),
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.CharField(default='Español', max_length=50),
        ),
    ]
