# Generated by Django 4.2.6 on 2024-08-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0023_movie_duration_movie_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
