# Generated by Django 4.2.6 on 2024-08-09 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0028_remove_movie_movie_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_language',
            field=models.CharField(default='Espanol', max_length=50),
        ),
    ]
